tracker_type: bytetrack
track_high_thresh: 0.20   # Accepte les détections dès 20% de confiance
track_low_thresh: 0.05
new_track_thresh: 0.25
track_buffer: 75          # Vos 75 frames de mémoire spatiale (Option A)
match_thresh: 0.75
fuse_score: True
