tracker_type: bytetrack
track_high_thresh: 0.20   # <-- Baisé à 0.20 pour garder les motos partiellement masquées
track_low_thresh: 0.05    # <-- Récupère même les détections très faibles lors des occultations
new_track_thresh: 0.25    # <-- Permet de valider rapidement l'entrée d'une nouvelle moto
track_buffer: 75          # OPTION A : Mémoire portée à 75 frames (~2.5s) contre les masquages
match_thresh: 0.75        # OPTION A : Association assouplie
fuse_score: True
